version: '3.0'

services:
  library:
    container_name: library
    build:
      context: .
      dockerfile: ./apps/library-service/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - "authors"
      - "publishers"
    command: npm run start:dev
  authors:
    container_name: authors
    build:
      context: .
      dockerfile: ./apps/authors-service/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    restart: always
    command: npm run start:dev authors-service
  publishers:
    container_name: publishers
    build:
      context: .
      dockerfile: ./apps/publishers-service/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3002:3002
    restart: always
    command: npm run start:dev publishers-service
